name: "PHPStan - CI"

on:
  push:
    paths:
      - ".github/workflows/phpstan.yml"

jobs:
  build:
    runs-on: ubuntu-latest

  steps:
    - name: Checkout project
    - uses: actions/checkout@v2
    - uses: php-actions/composer@v6
    - uses: php-actions/phpstan@v3
      with:
        configuration: phpstan.neon
